[web]
35.153.60.184 ansible_user=ec2-user ansible_ssh_private_key_file=key.pem ansible_connection=ssh ansible_python_interpreter=/usr/bin/python3.9

ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
